version: "3.8"
services:
    ld-konakart:
        build: 
            context: ./ld-konakart
        image: launchdarkly/konakart-demo:latest
        ports:
            - "8780:8780"
        environment:
            LD_DELAY_FLAG_KEY: <DELAY_FLAG_KEY>
            LD_ENV_SERVER_KEY: <ENV_SERVER_KEY>